# 🔢 NumPy In Python

## 📦 NumPy Import

In [1]:
import numpy as np

### 👉 ndarray (N-Dimensional Array)

### 1D (vector)

### 2D (matrix)

### 3D and more

## 🧩 NumPy Array Types

### 1️⃣ 1D Array

In [4]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.shape

(9,)

In [7]:
a.ndim

1

### 2️⃣ 2D Array

In [8]:
b = np.array([[1,2,3], [4,5,6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.shape

(2, 3)

In [11]:
b.ndim

2

### 3️⃣ 3D Array

In [12]:
c = np.array([[[1,2,3],[4,5,6]]])

In [13]:
c

array([[[1, 2, 3],
        [4, 5, 6]]])

In [14]:
c.shape

(1, 2, 3)

In [15]:
c.ndim

3

In [153]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [154]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
d.shape

(1, 4, 3)

In [19]:
d.ndim

3

In [20]:
e = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [21]:
e

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
e.shape

(2, 2, 3)

In [23]:
e.ndim

3

## 🔍 Array Information Methods

### ndim: Dimensions of array

In [24]:
a.ndim

1

In [25]:
b.ndim

2

In [26]:
c.ndim

3

In [27]:
d.ndim

3

In [28]:
e.ndim

3

### shape: Rows & columns

In [29]:
a.shape

(9,)

In [30]:
b.shape

(2, 3)

In [31]:
c.shape

(1, 2, 3)

In [32]:
d.shape

(1, 4, 3)

In [33]:
e.shape

(2, 2, 3)

### size: Total elements

In [34]:
b.size

6

In [35]:
a.size

9

In [36]:
c.size

6

In [37]:
d.size

12

In [38]:
e.size

12

### dtype: Data type

a.dtype

In [40]:
b.dtype

dtype('int64')

In [41]:
c.dtype

dtype('int64')

In [42]:
d.dtype

dtype('int64')

In [43]:
e.dtype

dtype('int64')

## 🛠️ Array Creation Functions

### array()

In [44]:
np.array([0,2,4,6,8])

array([0, 2, 4, 6, 8])

### zeros()

In [47]:
f = np.zeros(10)

In [48]:
f

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
f.ndim

1

In [50]:
g = np.zeros((3,2))

In [51]:
g

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
g.ndim

2

In [53]:
g.shape

(3, 2)

### ones()

In [54]:
h = np.ones(10)

In [55]:
h

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
h.ndim

1

In [57]:
h.dtype

dtype('float64')

In [58]:
i = np.ones((2,3))

In [59]:
i

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
i.shape

(2, 3)

In [61]:
i.ndim

2

### arange()

In [62]:
j = np.arange(1,10,2)

In [63]:
j

array([1, 3, 5, 7, 9])

In [64]:
j.ndim

1

In [65]:
j.shape

(5,)

### linspace()

In [66]:
k = np.linspace(1,10,5)

In [67]:
k

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [68]:
k.ndim

1

In [69]:
k.shape

(5,)

In [70]:
k.dtype

dtype('float64')

### identity()

In [71]:
l = np.identity(5)

In [72]:
l

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
l.shape

(5, 5)

In [74]:
l.ndim

2

In [77]:
# m = np.identity(2,3)

## 🔁 Reshaping & Structure Methods

### reshape()

In [78]:
m = np.array([1,2,3,4,5,6,7,8,9])

In [79]:
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
m.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### flatten(): 2D → 1D

In [82]:
m.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
n = np.array([[1,2,3],[4,5,6]])

In [84]:
n

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
n.flatten()

array([1, 2, 3, 4, 5, 6])

### ravel()

In [86]:
o = np.array([[1,2,3],[4,5,6]])

In [87]:
o

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
o.ravel()

array([1, 2, 3, 4, 5, 6])

### arange() and reshape()

In [89]:
p = np.arange(100,200,5).reshape(4,5)

In [90]:
p

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

## ➕➖➗ Arithmetic Operations

In [181]:
q = np.array([10,20,30,40,50])
r = np.array([1,2,3,4,5])

In [92]:
q + r

array([11, 22, 33, 44, 55])

In [93]:
q - r

array([ 9, 18, 27, 36, 45])

In [94]:
q * r

array([ 10,  40,  90, 160, 250])

In [95]:
q / r

array([10., 10., 10., 10., 10.])

In [97]:
q + 10

array([20, 30, 40, 50, 60])

## 🧮 Mathematical Functions

## Basic Function

### mean()

In [96]:
np.mean(a)

np.float64(5.0)

In [98]:
np.mean(b)

np.float64(3.5)

In [119]:
np.mean(c)

np.float64(3.5)

### min()

In [100]:
np.min(a)

np.int64(1)

In [101]:
np.min(b)

np.int64(1)

In [102]:
np.min(e)

np.int64(1)

### max()

In [103]:
np.max(a)

np.int64(9)

In [104]:
np.max(b)

np.int64(6)

In [105]:
np.max(c)

np.int64(6)

In [114]:
np.max(d)

np.int64(12)

### sum()

In [108]:
np.sum(a)

np.int64(45)

In [109]:
np.sum(b)

np.int64(21)

In [110]:
np.sum(c)

np.int64(21)

In [115]:
np.sum(d)

np.int64(78)

### median()

In [116]:
np.median(a)

np.float64(5.0)

In [117]:
np.median(o)

np.float64(3.5)

In [118]:
np.median(k)

np.float64(5.5)

## Advanced

### sqrt()

In [121]:
r = np.array([1,4,9,16,25,36,49])

In [122]:
r

array([ 1,  4,  9, 16, 25, 36, 49])

In [123]:
np.sqrt(r)

array([1., 2., 3., 4., 5., 6., 7.])

### log()

In [124]:
np.log(r)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 ])

In [125]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [126]:
np.log(p)

array([[4.60517019, 4.65396035, 4.70048037, 4.74493213, 4.78749174],
       [4.82831374, 4.86753445, 4.90527478, 4.94164242, 4.97673374],
       [5.01063529, 5.04342512, 5.07517382, 5.10594547, 5.13579844],
       [5.16478597, 5.19295685, 5.22035583, 5.24702407, 5.27299956]])

### exp()

In [127]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [128]:
np.exp(p)

array([[2.68811714e+43, 3.98951957e+45, 5.92097203e+47, 8.78750164e+49,
        1.30418088e+52],
       [1.93557604e+54, 2.87264955e+56, 4.26338995e+58, 6.32743171e+60,
        9.39074129e+62],
       [1.39370958e+65, 2.06844842e+67, 3.06984964e+69, 4.55606083e+71,
        6.76179381e+73],
       [1.00353918e+76, 1.48938420e+78, 2.21044214e+80, 3.28058702e+82,
        4.86882283e+84]])

In [129]:
np.exp(r)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 1.90734657e+21])

## 📊 Statistical Functions

### median()

In [130]:
np.median(a)

np.float64(5.0)

In [131]:
np.median(p)

np.float64(147.5)

In [132]:
np.median(r)

np.float64(16.0)

### std()

In [133]:
np.std(a)

np.float64(2.581988897471611)

In [134]:
np.std(p)

np.float64(28.83140648667699)

In [135]:
np.std(r)

np.float64(16.3707055437449)

### var()

In [136]:
np.var(p)

np.float64(831.25)

In [137]:
np.var(o)

np.float64(2.9166666666666665)

In [138]:
np.var(a)

np.float64(6.666666666666667)

In [139]:
np.var(d)

np.float64(11.916666666666666)

## 🎯 Indexing & Slicing

In [140]:
s = np.arange(100,200,5).reshape(4,5)

In [141]:
s

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

### Indexing

In [142]:
s[0]

array([100, 105, 110, 115, 120])

### Slicing

In [143]:
s[1:3]

array([[125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170]])

In [145]:
s[1:3, 1:4]

array([[130, 135, 140],
       [155, 160, 165]])

### 2D Indexing

In [144]:
s[1,3]

np.int64(140)

## 🔍 Boolean & Conditional Operations

In [146]:
a > 6

array([False, False, False, False, False, False,  True,  True,  True])

In [147]:
s > 150

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [148]:
s[s > 160]

array([165, 170, 175, 180, 185, 190, 195])

In [149]:
d[d <= 7]

array([1, 2, 3, 4, 5, 6, 7])

## 🔄 Sorting & Searching

### sort()

In [155]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
t = np.array([5,2,8,5,9,2,4,6,9,1,6,9,2,5,7,9])

In [157]:
t

array([5, 2, 8, 5, 9, 2, 4, 6, 9, 1, 6, 9, 2, 5, 7, 9])

In [159]:
np.sort(t)

array([1, 2, 2, 2, 4, 5, 5, 5, 6, 6, 7, 8, 9, 9, 9, 9])

### argsort()

In [160]:
np.argsort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [161]:
np.argsort(t)

array([ 9,  1, 12,  5,  6, 13,  3,  0,  7, 10, 14,  2,  4,  8, 11, 15])

In [162]:
np.argsort(b)

array([[0, 1, 2],
       [0, 1, 2]])

In [163]:
np.argsort(p)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### where()

In [164]:
np.where(d > 10)

(array([0, 0]), array([3, 3]), array([1, 2]))

In [165]:
np.where(a > 5)

(array([5, 6, 7, 8]),)

In [166]:
np.where(d < 6)

(array([0, 0, 0, 0, 0]), array([0, 0, 0, 1, 1]), array([0, 1, 2, 0, 1]))

## 🎲 Random Functions

### rand()

In [167]:
np.random.rand(3)

array([0.47506535, 0.61033011, 0.43380754])

In [168]:
np.random.rand(10)

array([0.30329796, 0.75043297, 0.57461451, 0.05612214, 0.99818006,
       0.37218833, 0.05398034, 0.2454096 , 0.79865956, 0.26648072])

### randint()

In [170]:
np.random.randint(1, 10)

7

In [173]:
np.random.randint(1, 10, size=5)

array([4, 5, 5, 9, 7], dtype=int32)

In [174]:
np.random.randint(1,10000)

6633

### seed()

In [177]:
np.random.seed(100)

## 🔗 Joining & Splitting Arrays

### concatenate()

In [183]:
np.concatenate((q, r))

array([10, 20, 30, 40, 50,  1,  2,  3,  4,  5])

### vstack()

In [182]:
np.vstack((q, r))

array([[10, 20, 30, 40, 50],
       [ 1,  2,  3,  4,  5]])

### hstack()

In [184]:
np.hstack((q, r))

array([10, 20, 30, 40, 50,  1,  2,  3,  4,  5])

### split()

In [186]:
np.split(a, 3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [188]:
np.split(b, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

## 🧱 Copy vs View

### View

In [189]:
b = a.view()

In [190]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
u = p.view()

In [192]:
u

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

### Copy

In [193]:
v = a.copy()

In [194]:
v

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
w = p.copy()

In [196]:
w

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

## 🧮 Advanced Mathematical Functions

### sin(), cos(), tan(), cot(), cosec(), sec()

In [197]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [198]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [199]:
np.tan(c)

array([[[ 1.55740772, -2.18503986, -0.14254654],
        [ 1.15782128, -3.38051501, -0.29100619]]])

In [201]:
np.sin(p)

array([[-0.50636564, -0.97053528, -0.04424268,  0.94543533,  0.58061118],
       [-0.61604046, -0.93010595,  0.08836869,  0.98023966,  0.46774516],
       [-0.71487643, -0.87331198,  0.21942526,  0.99779728,  0.34664946],
       [-0.8011346 , -0.80115264,  0.34662118,  0.99779928,  0.21945467]])